apiVersion: v1
kind: Service
metadata:
  name: simple-api-service
  namespace: simple-api
spec:
  type: NodePort
  selector:
    app: simple-api
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080