name: Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted   

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          # Forzar minúsculas para el nombre del paquete
          OWNER_LOWER=$(echo '${{ github.actor }}' | tr '[:upper:]' '[:lower:]')
          FULL_IMAGE="ghcr.io/${OWNER_LOWER}/simple-api"
          
          echo "Construyendo imagen: ${FULL_IMAGE}:${{ github.sha }}"
          
          docker build -t ${FULL_IMAGE}:${{ github.sha }} .
          docker tag ${FULL_IMAGE}:${{ github.sha }} ${FULL_IMAGE}:latest
          
          docker push ${FULL_IMAGE}:${{ github.sha }}
          docker push ${FULL_IMAGE}:latest
          
          # Guardar la variable para el siguiente step
          echo "FULL_IMAGE=${FULL_IMAGE}" >> $GITHUB_ENV